#pragma once

namespace Trinity
{
    namespace Code
    {
        enum class KeyCode : int
        {
            UNKNOWN = -1,

            TR_KEY_SPACE = 32,
            TR_KEY_APOSTROPHE = 39,
            TR_KEY_COMMA = 44,
            TR_KEY_MINUS = 45,
            TR_KEY_PERIOD = 46,
            TR_KEY_SLASH = 47,
            TR_KEY_D0 = 48,
            TR_KEY_D1 = 49,
            TR_KEY_D2 = 50,
            TR_KEY_D3 = 51,
            TR_KEY_D4 = 52,
            TR_KEY_D5 = 53,
            TR_KEY_D6 = 54,
            TR_KEY_D7 = 55,
            TR_KEY_D8 = 56,
            TR_KEY_D9 = 57,
            TR_KEY_SEMICOLON = 59,
            TR_KEY_EQUAL = 61,
            TR_KEY_A = 65,
            TR_KEY_B = 66,
            TR_KEY_C = 67,
            TR_KEY_D = 68,
            TR_KEY_E = 69,
            TR_KEY_F = 70,
            TR_KEY_G = 71,
            TR_KEY_H = 72,
            TR_KEY_I = 73,
            TR_KEY_J = 74,
            TR_KEY_K = 75,
            TR_KEY_L = 76,
            TR_KEY_M = 77,
            TR_KEY_N = 78,
            TR_KEY_O = 79,
            TR_KEY_P = 80,
            TR_KEY_Q = 81,
            TR_KEY_R = 82,
            TR_KEY_S = 83,
            TR_KEY_T = 84,
            TR_KEY_U = 85,
            TR_KEY_V = 86,
            TR_KEY_W = 87,
            TR_KEY_X = 88,
            TR_KEY_Y = 89,
            TR_KEY_Z = 90,
            TR_KEY_LEFT_BRACKET = 91,
            TR_KEY_BACK_SLASH = 92,
            TR_KEY_RIGHT_BRACKET = 93,
            TR_KEY_GRAVE_ACCENT = 96,
            TR_KEY_WORLD1 = 161,
            TR_KEY_WORLD2 = 162,
            TR_KEY_ESCAPE = 256,
            TR_KEY_ENTER = 257,
            TR_KEY_TAB = 258,
            TR_KEY_BACKSPACE = 259,
            TR_KEY_INSERT = 260,
            TR_KEY_DELETE = 261,
            TR_KEY_RIGHT = 262,
            TR_KEY_LEFT = 263,
            TR_KEY_DOWN = 264,
            TR_KEY_UP = 265,
            TR_KEY_PAGE_UP = 266,
            TR_KEY_PAGE_DOWN = 267,
            TR_KEY_HOME = 268,
            TR_KEY_END = 269,
            TR_KEY_CAPSLOCK = 280,
            TR_KEY_SCROLLLOCK = 281,
            TR_KEY_NUMLOCK = 282,
            TR_KEY_PRINTSCREEN = 283,
            TR_KEY_PAUSE = 284,
            TR_KEY_F1 = 290,
            TR_KEY_F2 = 291,
            TR_KEY_F3 = 292,
            TR_KEY_F4 = 293,
            TR_KEY_F5 = 294,
            TR_KEY_F6 = 295,
            TR_KEY_F7 = 296,
            TR_KEY_F8 = 297,
            TR_KEY_F9 = 298,
            TR_KEY_F10 = 299,
            TR_KEY_F11 = 300,
            TR_KEY_F12 = 301,
            TR_KEY_F13 = 302,
            TR_KEY_F14 = 303,
            TR_KEY_F15 = 304,
            TR_KEY_F16 = 305,
            TR_KEY_F17 = 306,
            TR_KEY_F18 = 307,
            TR_KEY_F19 = 308,
            TR_KEY_F20 = 309,
            TR_KEY_F21 = 310,
            TR_KEY_F22 = 311,
            TR_KEY_F23 = 312,
            TR_KEY_F24 = 313,
            TR_KEY_F25 = 314,
            TR_KEY_KP0 = 320,
            TR_KEY_KP1 = 321,
            TR_KEY_KP2 = 322,
            TR_KEY_KP3 = 323,
            TR_KEY_KP4 = 324,
            TR_KEY_KP5 = 325,
            TR_KEY_KP6 = 326,
            TR_KEY_KP7 = 327,
            TR_KEY_KP8 = 328,
            TR_KEY_KP9 = 329,
            TR_KEY_KEYPAD_DECIMAL = 330,
            TR_KEY_KEYPAD_DIVIDE = 331,
            TR_KEY_KEYPAD_MULTIPLY = 332,
            TR_KEY_KEYPAD_SUBTRACT = 333,
            TR_KEY_KEYPAD_ADD = 334,
            TR_KEY_KEYPAD_ENTER = 335,
            TR_KEY_KEYPAD_EQUAL = 336,
            TR_KEY_LEFT_SHIFT = 340,
            TR_KEY_LEFT_CONTROL = 341,
            TR_KEY_LEFT_ALT = 342,
            TR_KEY_LEFT_SUPER = 343,
            TR_KEY_RIGHT_SHIFT = 344,
            TR_KEY_RIGHT_CONTROL = 345,
            TR_KEY_RIGHT_ALT = 346,
            TR_KEY_RIGHT_SUPER = 347,
            TR_KEY_MENU = 348
        };

        enum class MouseCode : int
        {
            TR_BUTTON_0 = 0,
            TR_BUTTON_1 = 1,
            TR_BUTTON_2 = 2,
            TR_BUTTON_3 = 3,
            TR_BUTTON_4 = 4,
            TR_BUTTON_5 = 5,
            TR_BUTTON_6 = 6,
            TR_BUTTON_7 = 7,
            TR_BUTTON_LAST = TR_BUTTON_7,
            TR_BUTTON_LEFT = TR_BUTTON_0,
            TR_BUTTON_RIGHT = TR_BUTTON_1,
            TR_BUTTON_MIDDLE = TR_BUTTON_2
        };

        // Gamepad buttons (GLFW gamepad mapping compatible)
        enum class GamepadButton : int
        {
            TR_BUTTON_A = 0,
            TR_BUTTON_B = 1,
            TR_BUTTON_X = 2,
            TR_BUTTON_Y = 3,
            TR_BUTTON_LEFT_BUMPER = 4,
            TR_BUTTON_RIGHT_BUMPER = 5,
            TR_BUTTON_BACK = 6,
            TR_BUTTON_START = 7,
            TR_BUTTON_GUIDE = 8,
            TR_BUTTON_LEFT_THUMB = 9,
            TR_BUTTON_RIGHT_THUMB = 10,
            TR_BUTTON_DPAD_UP = 11,
            TR_BUTTON_DPAD_RIGHT = 12,
            TR_BUTTON_DPAD_DOWN = 13,
            TR_BUTTON_DPAD_LEFT = 14,
            TR_BUTTON_LAST = TR_BUTTON_DPAD_LEFT
        };

        // Gamepad axes (GLFW gamepad mapping compatible)
        enum class GamepadAxis : int
        {
            TR_AXIS_LEFT_X = 0,
            TR_AXIS_LEFT_Y = 1,
            TR_AXIS_RIGHT_X = 2,
            TR_AXIS_RIGHT_Y = 3,
            TR_AXIS_LEFT_TRIGGER = 4,
            TR_AXIS_RIGHT_TRIGGER = 5,
            TR_AXIS_LAST = TR_AXIS_RIGHT_TRIGGER
        };
    }
}