#pragma once

#include <imgui.h>

#include <Forge/Editor/IconsMaterialDesignIcons.h>

namespace Trinity
{
    static constexpr ImWchar k_IconRangeMin = ICON_MIN_MDI;
    static constexpr ImWchar k_IconRangeMax = ICON_MAX_MDI;
}

#define ICON_FA_FOLDER ICON_MDI_FOLDER
#define ICON_FA_FOLDER_OPEN ICON_MDI_FOLDER_OPEN
#define ICON_FA_FILE ICON_MDI_FILE
#define ICON_FA_IMAGE ICON_MDI_IMAGE
#define ICON_FA_CUBE ICON_MDI_CUBE_OUTLINE
#define ICON_FA_CAMERA ICON_MDI_CAMERA
#define ICON_FA_LIGHTBULB ICON_MDI_LIGHTBULB
#define ICON_FA_VOLUME_HIGH ICON_MDI_VOLUME_HIGH
#define ICON_FA_PLAY ICON_MDI_PLAY
#define ICON_FA_STOP ICON_MDI_STOP
#define ICON_FA_FLOPPY_DISK ICON_MDI_CONTENT_SAVE
#define ICON_FA_TRASH ICON_MDI_DELETE
#define ICON_FA_PLUS ICON_MDI_PLUS
#define ICON_FA_MINUS ICON_MDI_MINUS
#define ICON_FA_EXPAND ICON_MDI_FULLSCREEN
#define ICON_FA_COMPRESS ICON_MDI_FULLSCREEN_EXIT
#define ICON_FA_XMARK ICON_MDI_CLOSE
#define ICON_FA_WINDOW_MINIMIZE ICON_MDI_WINDOW_MINIMIZE
#define ICON_FA_WINDOW_MAXIMIZE ICON_MDI_WINDOW_MAXIMIZE
#define ICON_FA_WINDOW_RESTORE ICON_MDI_WINDOW_RESTORE
#define ICON_FA_WINDOW_CLOSE ICON_MDI_WINDOW_CLOSE
#define ICON_FA_EYE ICON_MDI_EYE
#define ICON_FA_SITEMAP ICON_MDI_SITEMAP
#define ICON_FA_SLIDERS ICON_MDI_TUNE
#define ICON_FA_TERMINAL ICON_MDI_CONSOLE
#define ICON_FA_CIRCLE_INFO ICON_MDI_INFORMATION
#define ICON_FA_TRIANGLE_EXCLAMATION ICON_MDI_ALERT
#define ICON_FA_ARROWS_ROTATE ICON_MDI_REFRESH
#define ICON_FA_GEAR ICON_MDI_COG
#define ICON_FA_UP_DOWN_LEFT_RIGHT ICON_MDI_CURSOR_MOVE
#define ICON_FA_COPY ICON_MDI_CONTENT_COPY
#define ICON_FA_PAINTBRUSH ICON_MDI_BRUSH
#define ICON_FA_ARROWS_UP_DOWN_LEFT_RIGHT ICON_MDI_AXIS_ARROW
#define ICON_FA_ROTATE ICON_MDI_ROTATE_ORBIT
#define ICON_FA_MAXIMIZE ICON_MDI_ARROW_EXPAND_ALL
#define ICON_FA_MAGNET ICON_MDI_MAGNET
#define ICON_FA_PEN ICON_MDI_PENCIL
#define ICON_FA_ELLIPSIS_VERTICAL ICON_MDI_DOTS_VERTICAL