#pragma once

#include <imgui.h>

#include <Forge/Editor/IconsMaterialDesignIcons.h>

namespace Trinity
{
    static constexpr ImWchar k_IconRangeMin = ICON_MIN_MDI;
    static constexpr ImWchar k_IconRangeMax = ICON_MAX_MDI;
}

#define ICON_FA_FOLDER ICON_MDI_FOLDER
#define ICON_FA_FOLDER_OPEN ICON_MDI_FOLDER_OPEN
#define ICON_FA_FILE ICON_MDI_FILE
#define ICON_FA_IMAGE ICON_MDI_IMAGE
#define ICON_FA_CUBE ICON_MDI_CUBE_OUTLINE
#define ICON_FA_CAMERA ICON_MDI_CAMERA
#define ICON_FA_LIGHTBULB ICON_MDI_LIGHTBULB
#define ICON_FA_VOLUME_HIGH ICON_MDI_VOLUME_HIGH
#define ICON_FA_PLAY ICON_MDI_PLAY
#define ICON_FA_STOP ICON_MDI_STOP
#define ICON_FA_FLOPPY_DISK ICON_MDI_CONTENT_SAVE
#define ICON_FA_TRASH ICON_MDI_DELETE
#define ICON_FA_PLUS ICON_MDI_PLUS
#define ICON_FA_MINUS ICON_MDI_MINUS
#define ICON_FA_EXPAND ICON_MDI_FULLSCREEN
#define ICON_FA_COMPRESS ICON_MDI_FULLSCREEN_EXIT
#define ICON_FA_XMARK ICON_MDI_CLOSE
#define ICON_FA_WINDOW_MINIMIZE ICON_MDI_WINDOW_MINIMIZE
#define ICON_FA_WINDOW_MAXIMIZE ICON_MDI_WINDOW_MAXIMIZE
#define ICON_FA_WINDOW_RESTORE ICON_MDI_WINDOW_RESTORE
#define ICON_FA_WINDOW_CLOSE ICON_MDI_WINDOW_CLOSE
#define ICON_FA_EYE ICON_MDI_EYE
#define ICON_FA_SITEMAP ICON_MDI_SITEMAP
#define ICON_FA_SLIDERS ICON_MDI_TUNE
#define ICON_FA_TERMINAL ICON_MDI_CONSOLE
#define ICON_FA_CIRCLE_INFO ICON_MDI_INFORMATION
#define ICON_FA_TRIANGLE_EXCLAMATION ICON_MDI_ALERT
#define ICON_FA_ARROWS_ROTATE ICON_MDI_REFRESH
#define ICON_FA_GEAR ICON_MDI_COG
#define ICON_FA_UP_DOWN_LEFT_RIGHT ICON_MDI_CURSOR_MOVE
#define ICON_FA_COPY ICON_MDI_CONTENT_COPY
#define ICON_FA_PAINTBRUSH ICON_MDI_BRUSH
#define ICON_FA_ARROWS_UP_DOWN_LEFT_RIGHT ICON_MDI_AXIS_ARROW
#define ICON_FA_ROTATE ICON_MDI_ROTATE_ORBIT
#define ICON_FA_MAXIMIZE ICON_MDI_ARROW_EXPAND_ALL
#define ICON_FA_MAGNET ICON_MDI_MAGNET
#define ICON_FA_PEN ICON_MDI_PENCIL
#define ICON_FA_ELLIPSIS_VERTICAL ICON_MDI_DOTS_VERTICAL
#define ICON_FA_VECTOR_SQUARE ICON_MDI_VECTOR_SQUARE
#define ICON_FA_ATOM ICON_MDI_ATOM
#define ICON_FA_CIRCLE_OUTLINE ICON_MDI_CIRCLE_OUTLINE

// Unity editor chrome. The ICON_FA_* names above are legacy aliases kept so the property panels keep compiling; new UI code uses the ICON_TR_* set
#define ICON_TR_PLAY ICON_MDI_PLAY
#define ICON_TR_PAUSE ICON_MDI_PAUSE
#define ICON_TR_STEP ICON_MDI_SKIP_NEXT
#define ICON_TR_SEARCH ICON_MDI_MAGNIFY
#define ICON_TR_CHEVRON_DOWN ICON_MDI_CHEVRON_DOWN
#define ICON_TR_PLUS ICON_MDI_PLUS
#define ICON_TR_SETTINGS ICON_MDI_COG
#define ICON_TR_MORE ICON_MDI_DOTS_VERTICAL
#define ICON_TR_LAYOUT ICON_MDI_VIEW_GRID_OUTLINE
#define ICON_TR_UNDO ICON_MDI_UNDO
#define ICON_TR_REDO ICON_MDI_REDO
#define ICON_TR_HISTORY ICON_MDI_HISTORY
#define ICON_TR_SAVE ICON_MDI_CONTENT_SAVE
#define ICON_TR_REFRESH ICON_MDI_REFRESH
#define ICON_TR_HELP ICON_MDI_HELP_CIRCLE_OUTLINE
#define ICON_TR_CLOUD ICON_MDI_CLOUD_OUTLINE

// Scene view tool handles, in Unity's Q/W/E/R/Y order.
#define ICON_TR_TOOL_VIEW ICON_MDI_HAND_BACK_RIGHT
#define ICON_TR_TOOL_MOVE ICON_MDI_ARROW_ALL
#define ICON_TR_TOOL_ROTATE ICON_MDI_ROTATE_3D_VARIANT
#define ICON_TR_TOOL_SCALE ICON_MDI_ARROW_EXPAND
#define ICON_TR_TOOL_TRANSFORM ICON_MDI_AXIS_ARROW
#define ICON_TR_GRIP ICON_MDI_DRAG_HORIZONTAL
#define ICON_TR_PIVOT ICON_MDI_CROSSHAIRS_GPS
#define ICON_TR_CENTER ICON_MDI_SET_CENTER
#define ICON_TR_LOCAL ICON_MDI_AXIS_ARROW
#define ICON_TR_GLOBAL ICON_MDI_EARTH
#define ICON_TR_SNAP ICON_MDI_GRID
#define ICON_TR_STATS ICON_MDI_CHART_BOX_OUTLINE
#define ICON_TR_CAMERA ICON_MDI_CAMERA

// Panel identity icons carried on the dock tabs.
#define ICON_TR_SCENE ICON_MDI_MOVIE_OPEN_OUTLINE
#define ICON_TR_GAME ICON_MDI_GAMEPAD_VARIANT_OUTLINE
#define ICON_TR_HIERARCHY ICON_MDI_FILE_TREE
#define ICON_TR_INSPECTOR ICON_MDI_TUNE_VERTICAL
#define ICON_TR_PROJECT ICON_MDI_FOLDER_OUTLINE
#define ICON_TR_CONSOLE ICON_MDI_CONSOLE
#define ICON_TR_GAMEOBJECT ICON_MDI_CUBE_OUTLINE

// Console / status bar severities.
#define ICON_TR_INFO ICON_MDI_INFORMATION
#define ICON_TR_WARNING ICON_MDI_ALERT
#define ICON_TR_ERROR ICON_MDI_ALERT_CIRCLE
#define ICON_TR_CLEAR ICON_MDI_DELETE_SWEEP
#define ICON_TR_COLLAPSE ICON_MDI_ARROW_COLLAPSE
#define ICON_TR_MUTE ICON_MDI_VOLUME_OFF
#define ICON_TR_GIZMOS ICON_MDI_VECTOR_SQUARE